version: '3.8'

services:
  bootnode:
    hostname: bootnode
    image: ethereum/client-go:alltools-v1.10.16
    restart: on-failure
    container_name: ${CONTAINER_PREFIX}-bootnode
    volumes:
      - ./eth_network/bootnode/bootnode.key:/tmp/bootnode.key
    command:
      bootnode
      -nodekey /tmp/bootnode.key
    networks:
      grid-network: {}

  contract-node:
    hostname: contract-node
    container_name: ${CONTAINER_PREFIX}-contract-node
    image: ${ETH_NODE_IMAGE}
    restart: on-failure
    build:
      context: eth_network
      dockerfile: miner/${ETH_NODE_DOCKERFILE}
    depends_on:
      - bootnode
      - ethstats
    volumes:
      - ./eth_network/contract-producer/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@bootnode:0?discport=30301"
      --networkid=${ETH_CHAIN_ID}
      --mine
      --miner.threads=1
      --http
      --http.api="personal,eth,admin,miner,web3"
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr="0.0.0.0"
      --http.port=8085
      --ethstats="contract-node:password@ws://ethstats:3000"
      --unlock=0xdb044d024331aa4a4a019cef625dfca419cf73df
      --password=/password.txt
    networks:
      grid-network: {}

  contract-producer:
    hostname: contract-producer
    image: contract-producer
    container_name: ${CONTAINER_PREFIX}-contract-producer
    restart: on-failure
    build:
      context: ContractProducer
      dockerfile: Dockerfile.local
    volumes:
      - ./eth_network/contract-producer/:/root/.ethereum/keystore
    environment:
      - WALLET_PATH=/root/.ethereum/keystore/
      - WALLET_PASSWORD=password
      - URL_SCHEME=http
      - URL_HOST=contract-node
      - URL_PORT=8085
      - CHAIN_ID=${ETH_CHAIN_ID}
    networks:
      grid-network: {}

  ethstats:
    hostname: ethstats
    image: puppeth/ethstats
    container_name: ${CONTAINER_PREFIX}-eth-stats
    environment:
      - WS_SECRET=password
    ports:
      - "${ETH_STATS_PORT}:3000"
    networks:
      grid-network: {}


  # Agents will be added in a separate Dockerfile as
  # this file is simply the pre-existing infrastructure that is expected to
  # exist prior to anyone joining the network

  agent1-node:
    hostname: agent1-node
    image: ${ETH_NODE_IMAGE}
    restart: on-failure
    container_name: ${CONTAINER_PREFIX}-node-agent-1
    build:
      context: eth_network
      dockerfile: miner/${ETH_NODE_DOCKERFILE}
    depends_on:
      - bootnode
    volumes:
      - ./eth_network/agent1/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@bootnode:0?discport=30301"
      --networkid=${ETH_CHAIN_ID}
      --mine
      --miner.threads=1
      --http
      --http.api="personal,eth,admin,miner"
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr="0.0.0.0"
      --http.port=8085
      --ethstats="agent-1-node:password@ws://ethstats:3000"
      --unlock=0x685fbc3ddae415d0a73031b4192f6f46b11f7735
      --password=/password.txt
    networks:
      grid-network: {}

  agent2-node:
    hostname: agent2-node
    image: ${ETH_NODE_IMAGE}
    restart: on-failure
    container_name: ${CONTAINER_PREFIX}-node-agent-2
    build:
      context: eth_network
      dockerfile: miner/${ETH_NODE_DOCKERFILE}
    depends_on:
      - bootnode
    volumes:
      - ./eth_network/agent2/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@bootnode:0?discport=30301"
      --networkid=${ETH_CHAIN_ID}
      --http
      --mine
      --miner.threads=1
      --http.api="personal,eth,admin,miner"
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr="0.0.0.0"
      --http.port=8085
      --ethstats="agent-2-node:password@ws://ethstats:3000"
      --unlock=0x293839697e7197e1e3ef553f4434edfa499791ee
      --password=/password.txt
    networks:
      grid-network: {}

  agent-one:
    hostname: agent-one
    image: grid-agent
    restart: on-failure
    container_name: ${CONTAINER_PREFIX}-agent-one
    build:
      context: Agent
      dockerfile: Dockerfile.local
    volumes:
      - ./eth_network/agent1/:/root/.ethereum/keystore
    environment:
      - NET_CHAIN_ID=31575
      - NET_SCHEME=http
      - NET_HOST=agent1-node
      - NET_PORT=8085
      - WEB3J_WALLET_PATH=/root/.ethereum/keystore
      - WEB3J_WALLET_PASSWORD=password
      - PRODUCTION_RATE=50
      - CONSUMPTION_RATE=100
    networks:
      grid-network: { }

  agent-two:
    hostname: agent-two
    image: grid-agent
    restart: on-failure
    container_name: ${CONTAINER_PREFIX}-agent-two
    build:
      context: Agent
      dockerfile: Dockerfile.local
    volumes:
      - ./eth_network/agent2/:/root/.ethereum/keystore
    environment:
      - NET_CHAIN_ID=31575
      - NET_SCHEME=http
      - NET_HOST=agent2-node
      - NET_PORT=8085
      - WEB3J_WALLET_PATH=/root/.ethereum/keystore
      - WEB3J_WALLET_PASSWORD=password
      - PRODUCTION_RATE=100
      - CONSUMPTION_RATE=50
    networks:
      grid-network: { }

networks:
  grid-network:
    driver: bridge
    name: ${GRID_NETWORK}
