version: '3'

services:
  bootnode:
    hostname: bootnode
    image: ethereum/client-go:alltools-v1.10.16
    volumes:
      - ./eth_network/bootnode/bootnode.key:/tmp/bootnode.key
    command:
      bootnode
      -nodekey /tmp/bootnode.key
    networks:
      local-eth-network:

  contract-node:
    hostname: contract-node
    image: miner-node
    build:
      context: eth_network
      dockerfile: miner/Dockerfile
    depends_on:
      - bootnode
    volumes:
      - ./eth_network/contract-producer/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@bootnode:0?discport=30301"
      --networkid=31575
      --mine
      --miner.threads=1
      --http
      --http.api="personal,eth,admin,miner"
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr="0.0.0.0"
      --http.port=8085
      --unlock=0xdb044d024331aa4a4a019cef625dfca419cf73df
      --password=/password.txt
    networks:
      local-eth-network:

  contract-producer:
    hostname: contract-producer
    image: contract-producer
    build:
      context: ContractProducer
      dockerfile: Dockerfile.local
    volumes:
      - ./eth_network/contract-producer/:/root/.ethereum/keystore
    environment:
      - WALLET_PATH=/root/.ethereum/keystore/
      - WALLET_PASSWORD=password
      - URL_SCHEME=http
      - URL_HOST=contract-node
      - URL_PORT=8085
      - CHAIN_ID=31575
    networks:
      local-eth-network:

  # Agents will be added in a seperate Dockerfile as
  # this file is simply the pre-existing infrastructure that is expected to
  # exist prior to anyone joining the network

  agent1-node:
    hostname: agent1-node
    image: miner-node
    build:
      context: eth_network
      dockerfile: miner/Dockerfile
    depends_on:
      - bootnode
    volumes:
      - ./eth_network/agent1/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@bootnode:0?discport=30301"
      --networkid=31575
      --mine
      --miner.threads=1
      --http
      --http.api="personal,eth,admin,miner"
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr="0.0.0.0"
      --http.port=8085
      --unlock=0x685fbc3ddae415d0a73031b4192f6f46b11f7735
      --password=/password.txt
    networks:
      local-eth-network:

  agent2-node:
    hostname: agent2-node
    image: miner-node
    build:
      context: eth_network
      dockerfile: miner/Dockerfile
    depends_on:
      - bootnode
    volumes:
      - ./eth_network/agent2/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@bootnode:0?discport=30301"
      --networkid=31575
      --http
      --mine
      --miner.threads=1
      --http.api="personal,eth,admin,miner"
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr="0.0.0.0"
      --http.port=8085
      --unlock=0x293839697e7197e1e3ef553f4434edfa499791ee
      --password=/password.txt
    networks:
      local-eth-network:


networks:
  local-eth-network:
    driver: bridge
