version: '3'

services:
  geth-bootnode:
    hostname: geth-bootnode
    image: bootnode
    build:
      context: .
      dockerfile: ./bootnode/Dockerfile
    volumes:
      - ./bootnode/bootnode.key:/tmp/bootnode.key
    command:
      --networkid=31575
    networks:
      local-eth-network:

  geth-miner:
    hostname: geth-miner
    image: miner-node
    build:
      context: .
      dockerfile: ./miner/Dockerfile
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - geth-bootnode
    volumes:
      - ./contract-producer/:/root/.ethereum/keystore
    command:
      --bootnodes="enode://2dc6792f1285b673f7c64182c7054c6190853ae06e8a9ae0e6daa1c68ebe543142a3ba2168bd0d540f9013967e47fb37dd0eac5c30fe13b3aed9ed66fa199bf2@geth-bootnode:30303"
      --networkid=31575
    networks:
      local-eth-network:

networks:
  local-eth-network:
    driver: bridge
