version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus
    ports:
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"


  graphana:
    image: grafana/grafana:latest
    container_name: graphana
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT


networks:
  monitoring:
    driver: bridge
