
# This Yaml file sets prometheus to scrape the /metrics endpoint
# exposed by cadvisor

global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      # The hostname will be resolved by docker
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
