micronaut:
  application:
    name: agent

blockchain:
  network:
    chainId: ${NET_CHAIN_ID:1}
    scheme: ${NET_SCHEME:http}
    host: ${NET_HOST:localhost}
    port: ${NET_PORT:8085}
  wallet:
    dir: ${WEB3J_WALLET_PATH:/Users/University/Desktop/Git/year3/cs347/agent1/keystore/}
    password: ${WEB3J_WALLET_PASSWORD:password}

